### PR TITLE
Add Minecraft java psa

### PR DESCRIPTION
**Pull request by NoozAbooz**
I suck at markdown so you'll need to add some stuff :p

### CODE REVIEW

**Comment by Botspot** [comment]
Good idea, but that's way too long.

It would cover most of the whole screen!

**Comment by NoozAbooz** [comment]
Lol, that's why I asked you to apply some markdown magic 😆

**Comment by Botspot** [comment]
> Lol, that's why I asked you to apply some markdown magic

Uhh, how would markdown make it smaller?

**Comment by NoozAbooz** [comment]
> > Lol, that's why I asked you to apply some markdown magic
> 
> Uhh, how would markdown make it smaller?

Add newlines?

**Comment by Botspot** [comment]
> > > Lol, that's why I asked you to apply some markdown magic
> > 
> > 
> > Uhh, how would markdown make it smaller?
> 
> Add newlines?

Nope, wouldn't help.  
Look:  
2021-01-04-192032_1920x1080_scrot

So in my commit, I basically shortened it as much as possible.

**Comment by NoozAbooz** [comment]
Ah ok then. Lots of text are still better than 10 issues about not being able to login.

**Comment by Botspot** [comment]
> Ah ok then. Lots of text are still better than 10 issues about not being able to login.

And 10 issues is better than bothering 100,000 people by covering half their screen. ;)

**Pull request merged**
